# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a963bcc37a143411319c465e955df08c6a56f87fae81c1c759a315a6734b8b7cc8a7217f6cc228b4b22b14441eb1d73ad9bd2df86ec4e68410a0c6d4a0f6bea7

test:
  secret_key_base: a87dd381ef4def1efae783ecfa660fbb4a1d3095a15816f129d0f024f8e07adfd32ba97a987dd1976fde94bf9742199b9ae9eb4764686da49d969dd9c379ce75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
